export const ADD_GOODS_TO_CART = "ADD_GOODS_TO_CART";

export const CHANGE_CURRENT_STATE = "CHANGE_CURRENT_STATE";

export const INIT_ALL_INPUT_STATE = "INIT_ALL_INPUT_STATE";

export const CHANGE_ALL_INPUT_STATE = "CHANGE_ALL_INPUT_STATE";
